version: '3'

services:
  mysql:
    image: mysql:8.0.30
    container_name: "mysql"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=laravel
      - MYSQL_DATABASE=laravel
      - MYSQL_PASSWORD=secret
    networks:
      - my-network

  laravelboil:
    build: .
    container_name: "boilerplate"
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - boilerplatedata:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    container_name: "nginx"
    restart: unless-stopped
    depends_on:
      - laravelboil
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - boilerplatedata:/var/www/html
      - ./nginx_app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
   mysqldata:
   boilerplatedata:
